language: ruby
rvm:
  - 2.1.10
  - 2.2.4
  - 2.3.0
  - 2.4.0
  - jruby-9.0.5.0
before_script:
  - export IS_TRAVIS=true
gemfile:
  - Gemfile
  - rails/Gemfile
deploy:
  provider: rubygems
  gem: qiniu
  api_key:
    secure: frhK5TRyrplKjwEktkjx4nGyXBhELae7B/rfDTWUqLrwX4Gmx2XTf0j3VSwKphf2PclW2Phs1o029JFjivgjCB0gYpb4/lgPLxXAjYoUv7cbyZ1SdvIkhJsxilPgkPOr/t6XZ4OB1WU0yLJxDKNyJCh6fHJ47OlMfy7neGPtFKI=
  on:
    tags: true
